# Generated by Django 3.2 on 2022-08-16 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unpack_ipv4=True)),
                ('dnsname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Uch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MonitoringIsp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiveddoc', models.PositiveSmallIntegerField()),
                ('received', models.PositiveSmallIntegerField()),
                ('monitoringdata', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('nomeruch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uch_isp', to='monitoring_isp.server', verbose_name='IP')),
            ],
        ),
        migrations.CreateModel(
            name='DbAmirs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.PositiveSmallIntegerField(default=3050)),
                ('pathtodb', models.CharField(max_length=500)),
                ('receiveddoc', models.PositiveSmallIntegerField()),
                ('opencase', models.PositiveSmallIntegerField()),
                ('login', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('ipserver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_dbamirs', to='monitoring_isp.server', verbose_name='IP')),
                ('nomeruch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uch_dbamirs', to='monitoring_isp.server', verbose_name='nomeruch')),
                ('servername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_dbamirs', to='monitoring_isp.server', verbose_name='servername')),
            ],
            options={
                'ordering': ['nomeruch'],
            },
        ),
    ]
