# Generated by Django 3.2 on 2022-08-17 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_isp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitoringisp',
            old_name='received',
            new_name='opencase',
        ),
        migrations.RemoveField(
            model_name='dbamirs',
            name='opencase',
        ),
        migrations.RemoveField(
            model_name='dbamirs',
            name='receiveddoc',
        ),
        migrations.AlterField(
            model_name='dbamirs',
            name='nomeruch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uch_dbamirs', to='monitoring_isp.uch', verbose_name='nomeruch'),
        ),
    ]
