# Generated by Django 3.2 on 2022-08-17 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_isp', '0002_auto_20220817_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbamirs',
            name='ipserver',
        ),
        migrations.RemoveField(
            model_name='dbamirs',
            name='servername',
        ),
        migrations.AddField(
            model_name='dbamirs',
            name='server',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='dbamirs', to='monitoring_isp.server', verbose_name='server'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monitoringisp',
            name='nomeruch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MonitoringIsp', to='monitoring_isp.uch', verbose_name='nomeruch'),
        ),
    ]
