# Generated by Django 3.2 on 2022-08-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_isp', '0003_auto_20220817_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbamirs',
            name='charset',
            field=models.CharField(default='WIN1251', max_length=100),
        ),
        migrations.AddField(
            model_name='dbamirs',
            name='sql_dialect',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
