# Generated by Django 3.2 on 2022-08-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_isp', '0004_auto_20220817_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbamirs',
            name='login',
            field=models.CharField(default='SYSDBA', max_length=100),
        ),
        migrations.AlterField(
            model_name='dbamirs',
            name='password',
            field=models.CharField(default='masterkey', max_length=100),
        ),
    ]
