# Generated by Django 3.2 on 2022-08-24 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_isp', '0005_auto_20220817_2021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uch',
            options={'ordering': ['numer']},
        ),
    ]
